Gym Core/Gym Core/Models/Membre.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace Gym_Core.Models
{
    public partial class Membre
    {
        public Membre()
        {
            Payements = new HashSet<Payement>();
        }

        public int Id { get; set; }
        public string NomMembre { get; set; }
        public string PrenomMembre { get; set; }
        public DateTime? DatenaissanceMembre { get; set; }
        public string ContactMembre { get; set; }
        public DateTime? DatejointureMembre { get; set; }
        public int? Groupe { get; set; }

        public virtual Groupe GroupeNavigation { get; set; }
        public virtual ICollection<Payement> Payements { get; set; }
    }
}

Gym Core/Gym Core/Controllers/MembresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Gym_Core.Models;

namespace Gym_Core.Controllers
{
    public class MembresController : Controller
    {
        private readonly GymContext _context;

        public MembresController(GymContext context)
        {
            _context = context;
        }

        // GET: Membres
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            ViewData["Groupe"] = new SelectList(_context.Groupes, "Id", "NomGroupe");
            return View(_context.Membres.Include(m => m.GroupeNavigation).ToList());
        }

        [HttpPost]
        public async Task<IActionResult> Index(int groupe)
        {
            if (groupe == null)
                return View(_context.Membres.Include(m => m.GroupeNavigation).ToList());
            else
            {
                ViewData["Groupe"] = new SelectList(_context.Groupes, "Id", "NomGroupe", groupe);
                return View(_context.Membres.Include(m => m.GroupeNavigation).Where(m => m.Groupe == groupe).ToList());
            }
        }

        // GET: Membres/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var membre = await _context.Membres
                .Include(m => m.GroupeNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (membre == null)
            {
                return NotFound();
            }
            membre.Payements = _context.Payements.Where(n => n.Membre == id).ToList();
            return View(membre);
        }

        // GET: Membres/Create
        public IActionResult Create()
        {
            ViewData["Groupe"] = new SelectList(_context.Groupes, "Id", "Id");
            return View();
        }

        // POST: Membres/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,NomMembre,PrenomMembre,DatenaissanceMembre,ContactMembre,DatejointureMembre,Groupe")] Membre membre)
        {
            if (ModelState.IsValid)
            {
                _context.Add(membre);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Groupe"] = new SelectList(_context.Groupes, "Id", "Id", membre.Groupe);
            return View(membre);
        }

        // GET: Membres/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var membre = await _context.Membres.FindAsync(id);
            if (membre == null)
            {
                return NotFound();
            }
            ViewData["Groupe"] = new SelectList(_context.Groupes, "Id", "Id", membre.Groupe);
            return View(membre);
        }

        // POST: Membres/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NomMembre,PrenomMembre,DatenaissanceMembre,ContactMembre,DatejointureMembre,Groupe")] Membre membre)
        {
            if (id != membre.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(membre);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MembreExists(membre.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Groupe"] = new SelectList(_context.Groupes, "Id", "Id", membre.Groupe);
            return View(membre);
        }

        // GET: Membres/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var membre = await _context.Membres
                .Include(m => m.GroupeNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (membre == null)
            {
                return NotFound();
            }

            return View(membre);
        }

        // POST: Membres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var membre = await _context.Membres.FindAsync(id);
            _context.Membres.Remove(membre);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MembreExists(int id)
        {
            return _context.Membres.Any(e => e.Id == id);
        }
    }
}

Gym Core/Gym Core/Controllers/PayementsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Gym_Core.Models;
using Microsoft.AspNetCore.Authorization;

namespace Gym_Core.Controllers
{
    public class PayementsController : Controller
    {
        private readonly GymContext _context;

        public PayementsController(GymContext context)
        {
            _context = context;
        }

        // GET: Payements
        //public async Task<IActionResult> Index()
        //{
        //    var gymContext = _context.Payements.Include(p => p.MembreNavigation);
        //    return View(await gymContext.ToListAsync());
        //}


        // GET: Membres
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            ViewData["Membre"] = new SelectList(_context.Membres, "Id", "NomMembre");
            return View(_context.Payements.Include(m => m.MembreNavigation).ToList());
        }

        [HttpPost]
        public async Task<IActionResult> Index(int membre)
        {
            if (membre == null)
                return View(_context.Payements.Include(m => m.MembreNavigation).ToList());
            else
            {
                ViewData["Membre"] = new SelectList(_context.Membres, "Id", "NomMembre", membre);
                return View(_context.Payements.Include(m => m.MembreNavigation).Where(m => m.Membre == membre).ToList());
            }
        }

        // GET: Payements/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var payement = await _context.Payements
                .Include(p => p.MembreNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (payement == null)
            {
                return NotFound();
            }

            return View(payement);
        }

        // GET: Payements/Create/id
        public IActionResult Create(int? id)
        {
            ViewData["Membre"] = new SelectList(_context.Membres, "Id", "NomMembre");
            if (id != null)
                ViewData["Membre"] = new SelectList(_context.Membres, "Id", "NomMembre", id);
            return View();
        }


        // POST: Payements/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,DatePayement,MontantPayement,DescriptionPayement,Membre")] Payement payement)
        {
            if (ModelState.IsValid)
            {
                payement.DatePayement = DateTime.Now;
                if(_context.Payements.Count() == 0)
                {
                    payement.Id = 1;
                }
                else
                {
                    payement.Id = _context.Payements.Max(u => u.Id) + 1;
                }
                _context.Add(payement);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Membre"] = new SelectList(_context.Membres, "Id", "Id", payement.Membre);
            return View(payement);
        }

        // GET: Payements/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var payement = await _context.Payements.FindAsync(id);
            if (payement == null)
            {
                return NotFound();
            }
            ViewData["Membre"] = new SelectList(_context.Membres, "Id", "Id", payement.Membre);
            return View(payement);
        }

        // POST: Payements/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,DatePayement,MontantPayement,DescriptionPayement,Membre")] Payement payement)
        {
            if (id != payement.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(payement);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PayementExists(payement.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Membre"] = new SelectList(_context.Membres, "Id", "Id", payement.Membre);
            return View(payement);
        }

        // GET: Payements/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var payement = await _context.Payements
                .Include(p => p.MembreNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (payement == null)
            {
                return NotFound();
            }

            return View(payement);
        }

        // POST: Payements/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var payement = await _context.Payements.FindAsync(id);
            _context.Payements.Remove(payement);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PayementExists(int id)
        {
            return _context.Payements.Any(e => e.Id == id);
        }
    }
}

Gym Core/Gym Core/Views/Membres/Create.cshtml
@model Gym_Core.Models.Membre

@{
    ViewData["Title"] = "Create";
}

<h1>Create member</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NomMembre" class="control-label"></label>
                <input asp-for="NomMembre" class="form-control" />
                <span asp-validation-for="NomMembre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrenomMembre" class="control-label"></label>
                <input asp-for="PrenomMembre" class="form-control" />
                <span asp-validation-for="PrenomMembre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DatenaissanceMembre" class="control-label"></label>
                <input asp-for="DatenaissanceMembre" class="form-control" />
                <span asp-validation-for="DatenaissanceMembre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactMembre" class="control-label"></label>
                <input asp-for="ContactMembre" class="form-control" />
                <span asp-validation-for="ContactMembre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DatejointureMembre" class="control-label"></label>
                <input asp-for="DatejointureMembre" class="form-control" />
                <span asp-validation-for="DatejointureMembre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Groupe" class="control-label"></label>
                <select asp-for="Groupe" class ="form-control" asp-items="ViewBag.Groupe"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="badge badge-pill badge-light" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Gym Core/Gym Core/Views/Membres/Delete.cshtml
@model Gym_Core.Models.Membre

@{
    ViewData["Title"] = "Delete";
}

<h3>Are you sure you want to delete this Member?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Nom
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NomMembre)
        </dd>
        <dt class = "col-sm-2">
            Prenom
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrenomMembre)
        </dd>
        <dt class = "col-sm-2">
            DAte de naissance
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DatenaissanceMembre)
        </dd>
        <dt class = "col-sm-2">
            Contact
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContactMembre)
        </dd>
        <dt class = "col-sm-2">
            Date jointure
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DatejointureMembre)
        </dd>
        <dt class = "col-sm-2">
            Groupe
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GroupeNavigation.NomGroupe)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a class="badge badge-pill badge-light" asp-action="Index">Back to List</a>
    </form>
</div>

Gym Core/Gym Core/Views/Membres/Details.cshtml
@model Gym_Core.Models.Membre

@{
    ViewData["Title"] = "Details";
}

<h1>Details Membre</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Nom
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NomMembre)
        </dd>
        <dt class="col-sm-2">
            Prenom 
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PrenomMembre)
        </dd>
        <dt class="col-sm-2">
            Date de naissance
        </dt>
        <dd class="col-sm-10">
            @Model.DatenaissanceMembre.Value.ToShortDateString()
        </dd>
        <dt class="col-sm-2">
            Contact
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ContactMembre)
        </dd>
        <dt class="col-sm-2">
            Date jointure
        </dt>
        <dd class="col-sm-10">
            @Model.DatejointureMembre.Value.ToShortDateString()
        </dd>
        <dt class="col-sm-2">
            Groupe
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.GroupeNavigation.NomGroupe)
        </dd>
    </dl>
</div>
<div>
    <a class="badge badge-pill badge-warning" asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a class="badge badge-pill badge-light" asp-action="Index">Back to List</a>
</div>



<hr />

<div>
    <h2> Payements de membre </h2>

    <table class="table text-light">
        <thead>
            <tr>
                <th>
                    Date payement
                </th>
                <th>
                    Montant de payement
                </th>
                <th>
                    Description de payement
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Payements)
            {
                <tr>
                    <td>
                        @item.DatePayement.Value.ToShortDateString()
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MontantPayement)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DescriptionPayement)
                    </td>
                    <td>
                        <a class="badge badge-pill badge-warning" asp-controller="Payements" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a class="badge badge-pill badge-info" asp-controller="Payements" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a class="badge badge-pill badge-danger" asp-controller="Payements" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>

Gym Core/Gym Core/Views/Membres/Edit.cshtml
@model Gym_Core.Models.Membre

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Membre</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="NomMembre" class="control-label"></label>
                <input asp-for="NomMembre" class="form-control" />
                <span asp-validation-for="NomMembre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrenomMembre" class="control-label"></label>
                <input asp-for="PrenomMembre" class="form-control" />
                <span asp-validation-for="PrenomMembre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DatenaissanceMembre" class="control-label"></label>
                <input asp-for="DatenaissanceMembre" class="form-control" />
                <span asp-validation-for="DatenaissanceMembre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactMembre" class="control-label"></label>
                <input asp-for="ContactMembre" class="form-control" />
                <span asp-validation-for="ContactMembre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DatejointureMembre" class="control-label"></label>
                <input asp-for="DatejointureMembre" class="form-control" />
                <span asp-validation-for="DatejointureMembre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Groupe" class="control-label"></label>
                <select asp-for="Groupe" class="form-control" asp-items="ViewBag.Groupe"></select>
                <span asp-validation-for="Groupe" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="badge badge-pill badge-light" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Gym Core/Gym Core/Views/Membres/Index.cshtml
@model IEnumerable<Gym_Core.Models.Membre>

@{
    ViewData["Title"] = "Index";
}

<h1>Les Membres</h1>
<hr />
<div>
    <form asp-action="Index">
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text">Groupe</span>
            </div>

            <select id="groupe" name="groupe" class="form-control" asp-items="ViewBag.Groupe"></select>
            <div class="input-group-append">
                <input type="submit" value="Chercher" class="btn btn-outline-light" />
            </div>
        </div>
    </form>
</div>

<table class="table text-light">
    <thead>
        <tr>
            <th>
                Nom Membre
            </th>
            <th>
                Prenom Membre
            </th>
            <th>
                Date de naissance
            </th>
            <th>
                Contact Membre
            </th>
            <th>
                Date jointure
            </th>
            <th>
                Groupe
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NomMembre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PrenomMembre)
                </td>
                <td>
                    @item.DatenaissanceMembre.Value.ToShortDateString()
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ContactMembre)
                </td>
                <td>
                    @item.DatejointureMembre.Value.ToShortDateString()
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.GroupeNavigation.NomGroupe)
                </td>
                <td>
                    <a class="badge badge-pill badge-warning" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a class="badge badge-pill badge-info" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a class="badge badge-pill badge-danger" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
        <tr class="text-center">
            <td colspan="7">
                <a class="badge badge-pill badge-primary" asp-action="Create">Create New Member</a>
            </td>
        </tr>
    </tbody>
</table>