Gym Management system/Gym Management system/Models/Utilisateur.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;

namespace Gym_Management_system.Models
{
    public class Utilisateur
    {
        public string nom_utilisateur { get; set; }
        public string motdepasse_utilisateur { get; set; }

        public int createUtilisateur(string nom, string motdepasse)
        {
            return DBAccess.Affect("INSERT INTO utilisateurs(nom_utilisateur, motdepasse_utilisateur) VALUES('" + nom + "','" + motdepasse + "')");
        }

        public int updateUtilisateur(string nom, string motdepasse, string nvnom)
        {
            return DBAccess.Affect("UPDATE utilisateurs SET nom_utilisateur = '" + nvnom + "', motdepasse_utilisateur = '" + motdepasse + "' WHERE nom_utilisateur = '" + nom + "'");
        }

        public int deleteUtilisateur(string nom)
        {
            return DBAccess.Affect("DELETE FROM utilisateurs WHERE nom_utilisateur = '" + nom + "'");
        }

        public void getUtilisateur(string nom)
        {
            DataRow dr = DBAccess.Read("SELECT * FROM utilisateurs WHERE nom_utilisateur = '" + nom + "'").Rows[0];
            if(dr != null)
            {
                this.nom_utilisateur = dr["nom_utilisateur"].ToString();
                this.motdepasse_utilisateur = dr["motdepasse_utilisateur"].ToString();
            }
        }

        DataTable Utilisateurs()
        {
            return DBAccess.Read("SELECT * FROM utilisateurs");
        }

    }
}

Gym Management system/Gym Management system/Controllers/UtilisateurController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Gym_Management_system.Models;

namespace Gym_Management_system.Controllers
{
    public class UtilisateurController : Controller
    {
        // GET: Login
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(FormCollection collection)
        {
            try
            {
                Utilisateur u = new Utilisateur();
                u.getUtilisateur(collection["nom_utilisateur"]);
                if (u.nom_utilisateur == collection["nom_utilisateur"] && u.motdepasse_utilisateur == collection["motdepasse_utilisateur"])
                {
                    Session.Add("User", "connected");
                    return RedirectToAction("Dashboard");
                }
                else
                    return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: Dashboard
        public ActionResult Dashboard()
        {
            if (Session["User"] != null)
                return View();
            else
                return RedirectToAction("Login");
        }

        public ActionResult Deconnect()
        {
            try
            {
                Session.Abandon();
                return RedirectToAction("Login");
            }
            catch
            {
                return View("Dashboard");
            }
        }



        // GET: Utilisateur
        public ActionResult Index()
        {
            return View();
        }

        // GET: Utilisateur/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Utilisateur/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Utilisateur/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                if(collection["conf"] == collection["motdepasse_utilisateur"] && collection["nom_utilisateur"] != "")
                {
                    Utilisateur u = new Utilisateur();
                    if (u.createUtilisateur(collection["nom_utilisateur"], collection["motdepasse_utilisateur"]) == 1)
                        return RedirectToAction("Index");
                    else
                        return View();
                }
                else
                    return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: Utilisateur/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Utilisateur/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Utilisateur/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Utilisateur/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Gym Management system/Gym Management system/Views/Utilisateur/Create.cshtml
@model Gym_Management_system.Models.Utilisateur

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
    <div class="form-horizontal">
        <h4>Utilisateur</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nom_utilisateur, "Nom d'utilisateur", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nom_utilisateur, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nom_utilisateur, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.motdepasse_utilisateur, "Mot de passe", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.motdepasse_utilisateur, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.motdepasse_utilisateur, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label for="conf">Confirmer mot de passe </label>
            <div>
                <input type="text" name="conf" id="conf" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Gym Management system/Gym Management system/Views/Utilisateur/Dashboard.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Dashboard</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div>
        @using (Html.BeginForm("Deconnect", "Utilisateur"))
        {
            @Html.AntiForgeryToken()
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Deconnect" class="btn btn-default" />
                </div>
            </div>
        }
    </div>
</body>
</html>

Gym Management system/Gym Management system/Views/Utilisateur/Index.cshtml
@model Gym_Management_system.Models.Utilisateur

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div>
        <h4>Utilisateur</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.nom_utilisateur)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.nom_utilisateur)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.motdepasse_utilisateur)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.motdepasse_utilisateur)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

Gym Management system/Gym Management system/Views/Utilisateur/Login.cshtml
@model Gym_Management_system.Models.Utilisateur

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Login Form</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.nom_utilisateur, "Nom d'utilisateur", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.nom_utilisateur, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.nom_utilisateur, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.motdepasse_utilisateur, "Mot de passe", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.motdepasse_utilisateur, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.motdepasse_utilisateur, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Login" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
</body>
</html>