Gym Core/Gym Core/Models/Groupe.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace Gym_Core.Models
{
    public partial class Groupe
    {
        public Groupe()
        {
            Membres = new HashSet<Membre>();
        }

        public int Id { get; set; }
        public string NomGroupe { get; set; }
        public string DescriptionGroupe { get; set; }

        public virtual ICollection<Membre> Membres { get; set; }
    }
}

Gym Core/Gym Core/Controllers/GroupesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Gym_Core.Models;

namespace Gym_Core.Controllers
{
    public class GroupesController : Controller
    {
        private readonly GymContext _context;

        public GroupesController(GymContext context)
        {
            _context = context;
        }

        // GET: Groupes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Groupes.ToListAsync());
        }

        // GET: Groupes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var groupe = await _context.Groupes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (groupe == null)
            {
                return NotFound();
            }
            groupe.Membres = _context.Membres.Where(n => n.Groupe == id).ToList();
            return View(groupe);
        }

        // GET: Groupes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Groupes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,NomGroupe,DescriptionGroupe")] Groupe groupe)
        {
            if (ModelState.IsValid)
            {
                _context.Add(groupe);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(groupe);
        }

        // GET: Groupes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var groupe = await _context.Groupes.FindAsync(id);
            if (groupe == null)
            {
                return NotFound();
            }
            return View(groupe);
        }

        // POST: Groupes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NomGroupe,DescriptionGroupe")] Groupe groupe)
        {
            if (id != groupe.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(groupe);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GroupeExists(groupe.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(groupe);
        }

        // GET: Groupes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var groupe = await _context.Groupes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (groupe == null)
            {
                return NotFound();
            }

            return View(groupe);
        }

        // POST: Groupes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var groupe = await _context.Groupes.FindAsync(id);
            _context.Groupes.Remove(groupe);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GroupeExists(int id)
        {
            return _context.Groupes.Any(e => e.Id == id);
        }
    }
}

Gym Core/Gym Core/Controllers/MembresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Gym_Core.Models;

namespace Gym_Core.Controllers
{
    public class MembresController : Controller
    {
        private readonly GymContext _context;

        public MembresController(GymContext context)
        {
            _context = context;
        }

        // GET: Membres
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            ViewData["Groupe"] = new SelectList(_context.Groupes, "Id", "NomGroupe");
            return View(_context.Membres.Include(m => m.GroupeNavigation).ToList());
        }

        [HttpPost]
        public async Task<IActionResult> Index(int groupe)
        {
            if (groupe == null)
                return View(_context.Membres.Include(m => m.GroupeNavigation).ToList());
            else
            {
                ViewData["Groupe"] = new SelectList(_context.Groupes, "Id", "NomGroupe", groupe);
                return View(_context.Membres.Include(m => m.GroupeNavigation).Where(m => m.Groupe == groupe).ToList());
            }
        }

        // GET: Membres/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var membre = await _context.Membres
                .Include(m => m.GroupeNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (membre == null)
            {
                return NotFound();
            }
            membre.Payements = _context.Payements.Where(n => n.Membre == id).ToList();
            return View(membre);
        }

        // GET: Membres/Create
        public IActionResult Create()
        {
            ViewData["Groupe"] = new SelectList(_context.Groupes, "Id", "Id");
            return View();
        }

        // POST: Membres/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,NomMembre,PrenomMembre,DatenaissanceMembre,ContactMembre,DatejointureMembre,Groupe")] Membre membre)
        {
            if (ModelState.IsValid)
            {
                _context.Add(membre);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Groupe"] = new SelectList(_context.Groupes, "Id", "Id", membre.Groupe);
            return View(membre);
        }

        // GET: Membres/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var membre = await _context.Membres.FindAsync(id);
            if (membre == null)
            {
                return NotFound();
            }
            ViewData["Groupe"] = new SelectList(_context.Groupes, "Id", "Id", membre.Groupe);
            return View(membre);
        }

        // POST: Membres/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NomMembre,PrenomMembre,DatenaissanceMembre,ContactMembre,DatejointureMembre,Groupe")] Membre membre)
        {
            if (id != membre.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(membre);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MembreExists(membre.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Groupe"] = new SelectList(_context.Groupes, "Id", "Id", membre.Groupe);
            return View(membre);
        }

        // GET: Membres/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var membre = await _context.Membres
                .Include(m => m.GroupeNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (membre == null)
            {
                return NotFound();
            }

            return View(membre);
        }

        // POST: Membres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var membre = await _context.Membres.FindAsync(id);
            _context.Membres.Remove(membre);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MembreExists(int id)
        {
            return _context.Membres.Any(e => e.Id == id);
        }
    }
}

Gym Core/Gym Core/Views/Groupes/Create.cshtml
@model Gym_Core.Models.Groupe

@{
    ViewData["Title"] = "Create";
}

<h1>Create Groupe</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NomGroupe" class="control-label"></label>
                <input asp-for="NomGroupe" class="form-control" />
                <span asp-validation-for="NomGroupe" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DescriptionGroupe" class="control-label"></label>
                <input asp-for="DescriptionGroupe" class="form-control" />
                <span asp-validation-for="DescriptionGroupe" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="badge badge-pill badge-light" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Gym Core/Gym Core/Views/Groupes/Delete.cshtml
@model Gym_Core.Models.Groupe

@{
    ViewData["Title"] = "Delete";
}

<h3>Are you sure you want to delete this Groupe?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Nom
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NomGroupe)
        </dd>
        <dt class = "col-sm-2">
            Description
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DescriptionGroupe)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a class="badge badge-pill badge-light" asp-action="Index">Back to List</a>
    </form>
</div>

Gym Core/Gym Core/Views/Groupes/Details.cshtml
@model Gym_Core.Models.Groupe 
@{
    ViewData["Title"] = "Details";
}

<h1>Details Groupes</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Nom
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NomGroupe)
        </dd>
        <dt class="col-sm-2">
            Description
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DescriptionGroupe)
        </dd>
    </dl>
</div>
<div>
    <a class="badge badge-pill badge-warning" asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a class="badge badge-pill badge-light" asp-action="Index">Back to List</a>
</div>

<hr />

<div>
    <h2> Membres de groupe </h2>

    <table class="table text-light">
        <thead>
            <tr>
                <th>
                    Nom Membre
                </th>
                <th>
                    Prenom Membre
                </th>
                <th>
                    Date de naissance
                </th>
                <th>
                    Contact
                </th>
                <th>
                    Date Jointure
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Membres)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.NomMembre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PrenomMembre)
                    </td>
                    <td>
                        @item.DatenaissanceMembre.Value.ToShortDateString()
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ContactMembre)
                    </td>
                    <td>
                        @item.DatejointureMembre.Value.ToShortDateString()
                    </td>
                    <td>
                        <a class="badge badge-pill badge-warning" asp-controller="Membres" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a class="badge badge-pill badge-info" asp-controller="Membres" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a class="badge badge-pill badge-danger" asp-controller="Membres" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>

Gym Core/Gym Core/Views/Groupes/Edit.cshtml
@model Gym_Core.Models.Groupe

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Groupe</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="NomGroupe" class="control-label"></label>
                <input asp-for="NomGroupe" class="form-control" />
                <span asp-validation-for="NomGroupe" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DescriptionGroupe" class="control-label"></label>
                <input asp-for="DescriptionGroupe" class="form-control" />
                <span asp-validation-for="DescriptionGroupe" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Edit Groupe" class="btn btn-warning" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="badge badge-pill badge-light" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Gym Core/Gym Core/Views/Groupes/Index.cshtml
@model IEnumerable<Gym_Core.Models.Groupe>
@{
    ViewData["Title"] = "Index";
}
<h1>Groupes</h1>
<p>
    <a asp-action="Create" class="badge badge-pill badge-primary">Create New Groupe</a>
</p>
<table class="table text-light">
    <thead>
        <tr>
            <th>
                Nom Groupe
            </th>
            <th>
                Description de groupe
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NomGroupe)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DescriptionGroupe)
            </td>
            <td>
                <a asp-action="Edit" class="badge badge-pill badge-warning" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" class="badge badge-pill badge-info" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" class="badge badge-pill badge-danger" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>